#pragma once
#include <windows.h>
#include <stddef.h>
#include <stdint.h>

/*
 * Embedded emoji artwork, generated by tools/build_emoji_images.py.
 *
 * Each record points at a PNG inside g_ys_emoji_image_blob.  The renderer
 * decodes one on first use and keeps the resulting bitmap in its cache, so a
 * symbol that has artwork here never needs the system emoji font -- which is
 * what makes country flags display as flags even when Windows' Region setting
 * suppresses the font's flag ligatures.
 *
 * Records are sorted by nothing in particular; look them up with
 * ys_emoji_image_find().  Artwork is Twemoji (CC-BY 4.0), see
 * THIRD_PARTY_NOTICES.md.
 */
typedef struct YSEmojiImageRecord {
    const WCHAR *text;
    uint32_t offset;
    uint32_t size;
} YSEmojiImageRecord;

/* This data is compiled as C11 while emoji_renderer.c (its only consumer) is
 * compiled as C++, so the declarations need C linkage to match. */
#ifdef __cplusplus
extern "C" {
#endif

extern const unsigned char g_ys_emoji_image_blob[];
extern const YSEmojiImageRecord g_ys_emoji_images[];
extern const size_t g_ys_emoji_image_count;
extern const size_t g_ys_emoji_image_blob_size;

#ifdef __cplusplus
}
#endif
